"""initial schema

Revision ID: 8496387d4e36
Revises: 
Create Date: 2026-07-05 23:27:44.953344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8496387d4e36'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('actor_type', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('measures',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('hedis_measure_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('primary_color', sa.String(length=16), nullable=False),
    sa.Column('support_phone', sa.String(length=32), nullable=False),
    sa.Column('support_email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('external_member_id', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('date_of_birth', sa.String(length=10), nullable=False),
    sa.Column('sex', sa.String(length=1), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('preferred_channel', sa.String(length=16), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('consent_sms', sa.Boolean(), nullable=False),
    sa.Column('consent_email', sa.Boolean(), nullable=False),
    sa.Column('consent_recorded_at', sa.DateTime(), nullable=True),
    sa.Column('alias', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'external_member_id', name='uq_tenant_external_member')
    )
    op.create_index(op.f('ix_members_external_member_id'), 'members', ['external_member_id'], unique=False)
    op.create_index(op.f('ix_members_tenant_id'), 'members', ['tenant_id'], unique=False)
    op.create_table('staff_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_staff_email')
    )
    op.create_index(op.f('ix_staff_users_email'), 'staff_users', ['email'], unique=False)
    op.create_index(op.f('ix_staff_users_tenant_id'), 'staff_users', ['tenant_id'], unique=False)
    op.create_table('tenant_measure_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['measure_code'], ['measures.code'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'measure_code', name='uq_tenant_measure')
    )
    op.create_index(op.f('ix_tenant_measure_configs_measure_code'), 'tenant_measure_configs', ['measure_code'], unique=False)
    op.create_index(op.f('ix_tenant_measure_configs_tenant_id'), 'tenant_measure_configs', ['tenant_id'], unique=False)
    op.create_table('care_gaps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('period', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('numerator_met', sa.Boolean(), nullable=False),
    sa.Column('safety_flag', sa.Boolean(), nullable=False),
    sa.Column('follow_up_due_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_to', sa.String(length=36), nullable=True),
    sa.Column('last_outreach_at', sa.DateTime(), nullable=True),
    sa.Column('next_outreach_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closure_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['measure_code'], ['measures.code'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id', 'measure_code', 'period', name='uq_member_measure_period')
    )
    op.create_index(op.f('ix_care_gaps_measure_code'), 'care_gaps', ['measure_code'], unique=False)
    op.create_index(op.f('ix_care_gaps_member_id'), 'care_gaps', ['member_id'], unique=False)
    op.create_index(op.f('ix_care_gaps_tenant_id'), 'care_gaps', ['tenant_id'], unique=False)
    op.create_table('magic_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_tokens_member_id'), 'magic_tokens', ['member_id'], unique=False)
    op.create_index(op.f('ix_magic_tokens_token_hash'), 'magic_tokens', ['token_hash'], unique=False)
    op.create_table('case_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_gap_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['staff_users.id'], ),
    sa.ForeignKeyConstraint(['care_gap_id'], ['care_gaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_notes_care_gap_id'), 'case_notes', ['care_gap_id'], unique=False)
    op.create_table('outreach_attempts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_gap_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('template_code', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('error', sa.String(length=500), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_gap_id'], ['care_gaps.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outreach_attempts_care_gap_id'), 'outreach_attempts', ['care_gap_id'], unique=False)
    op.create_index(op.f('ix_outreach_attempts_member_id'), 'outreach_attempts', ['member_id'], unique=False)
    op.create_table('screening_submissions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('care_gap_id', sa.String(length=36), nullable=False),
    sa.Column('member_id', sa.String(length=36), nullable=False),
    sa.Column('measure_code', sa.String(length=32), nullable=False),
    sa.Column('instrument_scores', sa.JSON(), nullable=False),
    sa.Column('safety_flag', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['care_gap_id'], ['care_gaps.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_screening_submissions_care_gap_id'), 'screening_submissions', ['care_gap_id'], unique=False)
    op.create_index(op.f('ix_screening_submissions_member_id'), 'screening_submissions', ['member_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_screening_submissions_member_id'), table_name='screening_submissions')
    op.drop_index(op.f('ix_screening_submissions_care_gap_id'), table_name='screening_submissions')
    op.drop_table('screening_submissions')
    op.drop_index(op.f('ix_outreach_attempts_member_id'), table_name='outreach_attempts')
    op.drop_index(op.f('ix_outreach_attempts_care_gap_id'), table_name='outreach_attempts')
    op.drop_table('outreach_attempts')
    op.drop_index(op.f('ix_case_notes_care_gap_id'), table_name='case_notes')
    op.drop_table('case_notes')
    op.drop_index(op.f('ix_magic_tokens_token_hash'), table_name='magic_tokens')
    op.drop_index(op.f('ix_magic_tokens_member_id'), table_name='magic_tokens')
    op.drop_table('magic_tokens')
    op.drop_index(op.f('ix_care_gaps_tenant_id'), table_name='care_gaps')
    op.drop_index(op.f('ix_care_gaps_member_id'), table_name='care_gaps')
    op.drop_index(op.f('ix_care_gaps_measure_code'), table_name='care_gaps')
    op.drop_table('care_gaps')
    op.drop_index(op.f('ix_tenant_measure_configs_tenant_id'), table_name='tenant_measure_configs')
    op.drop_index(op.f('ix_tenant_measure_configs_measure_code'), table_name='tenant_measure_configs')
    op.drop_table('tenant_measure_configs')
    op.drop_index(op.f('ix_staff_users_tenant_id'), table_name='staff_users')
    op.drop_index(op.f('ix_staff_users_email'), table_name='staff_users')
    op.drop_table('staff_users')
    op.drop_index(op.f('ix_members_tenant_id'), table_name='members')
    op.drop_index(op.f('ix_members_external_member_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_table('tenants')
    op.drop_table('measures')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
