"""add member conditions field

Revision ID: c4524f2e16f1
Revises: 8496387d4e36
Create Date: 2026-07-06 00:10:39.360029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4524f2e16f1'
down_revision: Union[str, None] = '8496387d4e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('conditions', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('members', 'conditions')
    # ### end Alembic commands ###
